### PR TITLE
Allow to use predefined EdmProvider for Spring Boot compatibility

### PR DESCRIPTION
**Pull request by Falseclock**
Allow to use predefined EdmProvider and fix SAP/olingo-jpa-processor-v4/issues/34

### CODE REVIEW

**Comment by Falseclock** [comment]
this is also for Spring Boot compatibility.

**Comment by reket** [comment]
@wog48 could you please review this pull request and merge if all is ok? We are trying to build our api using Spring boot, but have problems with configuration and this changes should fix them. Thanks!

**Comment by emanov** [comment]
> @wog48 could you please review this pull request and merge if all is ok? We are trying to build our api using Spring boot, but have problems with configuration and this changes should fix them. Thanks!

Shouldn't Nurlan to sign  GitHub "Contributor License Agreement" before review?
"license/cla Pending — Contributor License Agreement is not signed yet."

Waiting for merge too.

**Comment by Falseclock** [comment]
> Shouldn't Nurlan to sign GitHub "Contributor License Agreement" before review?
I'm here )) 
already signed. But github has buggy signing procudure. It checks First and Last name instead of checking email. 

image

**Comment by wog48** [comment]
@emanov  please have a look at my last reply to [issues/34](https://github.com/SAP/olingo-jpa-processor-v4/issues/34). Do you have a similar problem and does the provided proposal solves it? 
I struggle merging this pull request, because the basic idea is that you do not need to do this. With that a need for injecting EdmProvider indicates another error.

**Comment by Falseclock** [comment]
incompatible with 0.3.4

**Pull request closed without merging**
